# Generated by Django 5.2.8 on 2025-12-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['id'], 'verbose_name': 'wizyta', 'verbose_name_plural': 'wizyty'},
        ),
    ]
