# Generated by Django 5.2.8 on 2025-11-23 22:10

import beauty_salon.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(blank=True, default=beauty_salon.utils.generate_client_number, max_length=20, null=True, unique=True, verbose_name='numer klienta'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.CharField(blank=True, default=beauty_salon.utils.generate_employee_number, max_length=20, null=True, unique=True, verbose_name='numer pracownika'),
        ),
    ]
