# Generated by Django 5.0.14 on 2025-11-11 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urlop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('typ', models.CharField(choices=[('urlop', 'Urlop'), ('choroba', 'Choroba'), ('osobiste', 'Osobiste/Inne')], max_length=20, verbose_name='typ')),
                ('status', models.CharField(choices=[('oczekujacy', 'Oczekujący'), ('zatwierdzony', 'Zatwierdzony'), ('odrzucony', 'Odrzucony')], default='oczekujacy', max_length=20, verbose_name='status')),
                ('data_od', models.DateField(verbose_name='data od')),
                ('data_do', models.DateField(verbose_name='data do')),
                ('powod', models.TextField(blank=True, verbose_name='powód/opis')),
                ('data_zatwierdzenia', models.DateTimeField(blank=True, null=True, verbose_name='data zatwierdzenia')),
            ],
            options={
                'verbose_name': 'urlop/niedostępność',
                'verbose_name_plural': 'urlopy/niedostępności',
                'db_table': 'urlopy',
            },
        ),
        migrations.RemoveConstraint(
            model_name='wizyta',
            name='no_employee_overlap',
        ),
        migrations.RemoveField(
            model_name='grafik',
            name='urlopy',
        ),
        migrations.AddConstraint(
            model_name='wizyta',
            constraint=models.CheckConstraint(check=models.Q(('termin_koniec__gt', models.F('termin_start'))), name='wizyty_end_after_start'),
        ),
        migrations.AddField(
            model_name='urlop',
            name='pracownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urlopy', to='beauty_salon.pracownik', verbose_name='pracownik'),
        ),
        migrations.AddField(
            model_name='urlop',
            name='zatwierdzony_przez',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zatwierdzone_urlopy', to=settings.AUTH_USER_MODEL),
        ),
    ]
