# Generated by Django 5.2.8 on 2025-11-22 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'notatka', 'verbose_name_plural': 'notatki'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Anulowane przez'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='beauty_salon.client', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='beauty_salon.employee', verbose_name='Pracownik'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='beauty_salon.service', verbose_name='Usługa'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Konto użytkownika'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employees', to='beauty_salon.service', verbose_name='Kompetencje'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Konto użytkownika'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='beauty_salon.appointment', verbose_name='Wizyta'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='beauty_salon.client', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_assets', to='beauty_salon.employee', verbose_name='Pracownik'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='note',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='beauty_salon.appointment', verbose_name='Wizyta'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='beauty_salon.appointment', verbose_name='Wizyta'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='beauty_salon.client', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='beauty_salon.appointment', verbose_name='Wizyta'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='reportpdf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='reportpdf',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Wygenerowane przez'),
        ),
        migrations.AlterField(
            model_name='reportpdf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='beauty_salon.employee', verbose_name='Pracownik'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='statssnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='statssnapshot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modyfikacje_ustawien', to=settings.AUTH_USER_MODEL, verbose_name='Ostatnia modyfikacja przez'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_offs', to=settings.AUTH_USER_MODEL, verbose_name='Zatwierdzone przez'),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='beauty_salon.employee', verbose_name='Pracownik'),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano'),
        ),
    ]
