# Generated by Django 5.2.7 on 2025-11-10 23:38

import beauty_salon.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='nr',
            field=models.CharField(db_index=True, default=beauty_salon.models.generate_employee_number, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^EMP-\\d{4}$', 'Format numeru: EMP-0001')], verbose_name='numer pracownika'),
        ),
    ]
