# Generated by Django 5.2.8 on 2025-12-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beauty_salon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="hired_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
