# Generated by Django 5.2.8 on 2025-12-23 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0002_alter_employeeprofile_hired_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_employee_end',
        ),
    ]
