# Generated by Django 5.2.8 on 2025-12-23 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0003_remove_appointment_unique_employee_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='client_number',
            field=models.CharField(blank=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Client number must be exactly 8 digits (e.g. 00000001).', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_number',
            field=models.CharField(blank=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Employee number must be exactly 8 digits (e.g. 00000001).', regex='^\\d{8}$')]),
        ),
    ]
