# Generated by Django 5.2.8 on 2025-12-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beauty_salon", "0004_alter_clientprofile_client_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
