# Generated by Django 5.2.8 on 2025-12-25 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0008_alter_clientprofile_client_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='beauty_salon.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='beauty_salon.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Oczekująca'), ('CONFIRMED', 'Potwierdzona'), ('COMPLETED', 'Zakończona'), ('CANCELLED', 'Anulowana')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('SERVICE_CREATED', 'Service created'), ('SERVICE_UPDATED', 'Service updated'), ('SERVICE_DISABLED', 'Service disabled'), ('SERVICE_ENABLED', 'Service enabled'), ('EMPLOYEE_CREATED', 'Employee created'), ('EMPLOYEE_UPDATED', 'Employee updated'), ('EMPLOYEE_DEACTIVATED', 'Employee deactivated'), ('CLIENT_CREATED', 'Client created'), ('CLIENT_UPDATED', 'Client updated'), ('CLIENT_DEACTIVATED', 'Client deactivated'), ('APPOINTMENT_CREATED', 'Appointment created'), ('APPOINTMENT_UPDATED', 'Appointment updated'), ('APPOINTMENT_CONFIRMED', 'Appointment confirmed'), ('APPOINTMENT_CANCELLED', 'Appointment cancelled'), ('APPOINTMENT_COMPLETED', 'Appointment completed'), ('TIMEOFF_CREATED', 'Time off created'), ('TIMEOFF_APPROVED', 'Time off approved'), ('TIMEOFF_REJECTED', 'Time off rejected'), ('AUTH_LOGIN', 'User login'), ('AUTH_LOGOUT', 'User logout'), ('SETTINGS_UPDATED', 'Settings updated')], db_index=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'start'], name='beauty_salo_client__db4e24_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['performed_by', 'timestamp'], name='beauty_salo_perform_2f6e70_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['target_user', 'timestamp'], name='beauty_salo_target__279f39_idx'),
        ),
    ]
