# Generated by Django 5.2.8 on 2025-12-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beauty_salon", "0011_alter_clientprofile_client_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Oczekująca"),
                    ("CONFIRMED", "Potwierdzona"),
                    ("COMPLETED", "Zakończona"),
                    ("CANCELLED", "Anulowana"),
                    ("NO_SHOW", "Nieobecność (no-show)"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="systemlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("SERVICE_CREATED", "Service created"),
                    ("SERVICE_UPDATED", "Service updated"),
                    ("SERVICE_DISABLED", "Service disabled"),
                    ("SERVICE_ENABLED", "Service enabled"),
                    ("EMPLOYEE_CREATED", "Employee created"),
                    ("EMPLOYEE_UPDATED", "Employee updated"),
                    ("EMPLOYEE_DEACTIVATED", "Employee deactivated"),
                    ("CLIENT_CREATED", "Client created"),
                    ("CLIENT_UPDATED", "Client updated"),
                    ("CLIENT_DEACTIVATED", "Client deactivated"),
                    ("APPOINTMENT_CREATED", "Appointment created"),
                    ("APPOINTMENT_UPDATED", "Appointment updated"),
                    ("APPOINTMENT_CONFIRMED", "Appointment confirmed"),
                    ("APPOINTMENT_CANCELLED", "Appointment cancelled"),
                    ("APPOINTMENT_COMPLETED", "Appointment completed"),
                    ("APPOINTMENT_NO_SHOW", "Appointment no-show"),
                    ("TIMEOFF_CREATED", "Time off created"),
                    ("TIMEOFF_APPROVED", "Time off approved"),
                    ("TIMEOFF_REJECTED", "Time off rejected"),
                    ("TIMEOFF_CANCELLED", "Time off cancelled"),
                    ("AUTH_LOGIN", "User login"),
                    ("AUTH_LOGOUT", "User logout"),
                    ("AUTH_PASSWORD_CHANGE", "User password change"),
                    ("SETTINGS_UPDATED", "Settings updated"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="timeoff",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Oczekuje"),
                    ("APPROVED", "Zaakceptowany"),
                    ("REJECTED", "Odrzucony"),
                    ("CANCELLED", "Anulowany"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
