# Generated by Django 5.2.8 on 2025-12-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "beauty_salon",
            "0012_alter_appointment_status_alter_systemlog_action_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["start"],
                "verbose_name": "Wizyta",
                "verbose_name_plural": "Wizyty",
            },
        ),
        migrations.AlterModelOptions(
            name="clientprofile",
            options={
                "ordering": ["pk"],
                "verbose_name": "Profil klienta",
                "verbose_name_plural": "Profile klientów",
            },
        ),
        migrations.AlterModelOptions(
            name="employeeprofile",
            options={
                "ordering": ["pk"],
                "verbose_name": "Profil pracownika",
                "verbose_name_plural": "Profile pracowników",
            },
        ),
        migrations.AlterModelOptions(
            name="employeeschedule",
            options={
                "ordering": ["pk"],
                "verbose_name": "Grafik pracownika",
                "verbose_name_plural": "Grafiki pracowników",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["pk"],
                "verbose_name": "Usługa",
                "verbose_name_plural": "Usługi",
            },
        ),
        migrations.AlterModelOptions(
            name="systemlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Log systemowy",
                "verbose_name_plural": "Logi systemowe",
            },
        ),
        migrations.AlterModelOptions(
            name="systemsettings",
            options={
                "verbose_name": "Ustawienia systemu",
                "verbose_name_plural": "Ustawienia systemu",
            },
        ),
        migrations.AlterModelOptions(
            name="timeoff",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Urlop/Nieobecność",
                "verbose_name_plural": "Urlopy/Nieobecności",
            },
        ),
        migrations.RemoveIndex(
            model_name="systemlog",
            name="beauty_salo_target__279f39_idx",
        ),
        migrations.AlterField(
            model_name="systemlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("SERVICE_CREATED", "Utworzono usługę"),
                    ("SERVICE_UPDATED", "Zaktualizowano usługę"),
                    ("APPOINTMENT_CREATED", "Utworzono wizytę"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
