# Generated by Django 6.0 on 2025-12-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0014_alter_systemlog_action'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_employee_start',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED'])), fields=('employee', 'start'), name='unique_employee_start_active'),
        ),
    ]
