# Generated by Django 6.0 on 2025-12-31 10:46

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def forwards_fix_null_clients(apps, schema_editor):
    """
    Tworzy klienta systemowego i przypina go do wszystkich Appointment(client IS NULL),
    żeby dało się bezpiecznie zrobić NOT NULL (PROTECT) na polu client.
    """
    Appointment = apps.get_model("beauty_salon", "Appointment")
    ClientProfile = apps.get_model("beauty_salon", "ClientProfile")
    CustomUser = apps.get_model("beauty_salon", "CustomUser")

    # Jeśli nie ma NULL-i, nic nie rób
    if not Appointment.objects.filter(client__isnull=True).exists():
        return

    # Znajdź wolny username zgodny z patternem klient-00000000
    username = None
    for i in range(0, 10000):
        candidate = f"klient-{i:08d}"
        if not CustomUser.objects.filter(username=candidate).exists():
            username = candidate
            break

    if username is None:
        raise RuntimeError("Brak wolnego username dla klienta systemowego.")

    system_user = CustomUser.objects.create(
        username=username,
        role="CLIENT",
        is_active=False,
        date_joined=timezone.now(),
    )

    system_client = ClientProfile.objects.create(
        user=system_user,
        first_name="Nieznany",
        last_name="Klient",
        email=None,
    )

    Appointment.objects.filter(client__isnull=True).update(client=system_client)


class Migration(migrations.Migration):

    dependencies = [
        ("beauty_salon", "0015_remove_appointment_unique_employee_start_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_fix_null_clients, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="beauty_salon.clientprofile",
            ),
        ),
    ]
